language: python
python:
  - "3.7"
install:
  - "pip install pipenv"
  - "pipenv lock"
  - "pipenv sync --dev"
script:
  - "pipenv run pyflakes *.py core/*.py modules/*.py"
  - "pipenv run python -m pytest"
